// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKEkigaMhQbq1qXnmRpoVLuUT1ZEwXGE',
    appId: '1:9214540785:web:147794a0e742200f0b6250',
    messagingSenderId: '9214540785',
    projectId: 'sppdn-beacukai',
    authDomain: 'sppdn-beacukai.firebaseapp.com',
    storageBucket: 'sppdn-beacukai.firebasestorage.app',
    measurementId: 'G-7VKSS9Z4PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqsFslz5diItstaAqukhQJLZ3NpQ5B7UY',
    appId: '1:9214540785:android:876ec56a573817850b6250',
    messagingSenderId: '9214540785',
    projectId: 'sppdn-beacukai',
    storageBucket: 'sppdn-beacukai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgZQyVC8fKDE2AWsCRdv3yK6Xv39XyUY',
    appId: '1:9214540785:ios:ad323b41f44b1d630b6250',
    messagingSenderId: '9214540785',
    projectId: 'sppdn-beacukai',
    storageBucket: 'sppdn-beacukai.firebasestorage.app',
    iosBundleId: 'beacukai.go.id.sppdn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgZQyVC8fKDE2AWsCRdv3yK6Xv39XyUY',
    appId: '1:9214540785:ios:ad323b41f44b1d630b6250',
    messagingSenderId: '9214540785',
    projectId: 'sppdn-beacukai',
    storageBucket: 'sppdn-beacukai.firebasestorage.app',
    iosBundleId: 'beacukai.go.id.sppdn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjKEkigaMhQbq1qXnmRpoVLuUT1ZEwXGE',
    appId: '1:9214540785:web:e5cae049c916dd500b6250',
    messagingSenderId: '9214540785',
    projectId: 'sppdn-beacukai',
    authDomain: 'sppdn-beacukai.firebaseapp.com',
    storageBucket: 'sppdn-beacukai.firebasestorage.app',
    measurementId: 'G-V18GH44T71',
  );
}
